config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order(:created_at)
  end

  def new
    @post = Post.new
  end

  def create
    post = current_user.posts.create!(post_params)
    redirect_to post
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  def update; end

  def destroy; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    if controller_name == 'texts' && action_name == 'show'
      'mw-md'
    # Devise 導入後にコメントアウトを解除
    elsif devise_controller?
      'mw-sm'
    else
      'mw-xl'
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#">世界遺産学習アプリ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          国別リスト
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">アジア</a>
          <a class="dropdown-item" href="#">オセアニア</a>
          <a class="dropdown-item" href="#">ヨーロッパ</a>
          <a class="dropdown-item" href="#">アフリカ</a>
          <a class="dropdown-item" href="#">北米</a>
          <a class="dropdown-item" href="#">南米</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          遺産クイズ
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">3級編</a>
          <a class="dropdown-item" href="#">2級編</a>
          <a class="dropdown-item" href="#">1級編</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          マイページ
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">メモ</a>
          <a class="dropdown-item" href="#">進捗管理</a>
          <a class="dropdown-item" href="#">アカウント編集</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">ログアウト</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioWorldApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <hr>
    <main>
    <%= render "layouts/flash"%>
      <%# max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <%= form.label :content %>
  <%= form.text_field :content, required: true %>
  <%= form.submit "送信" %>
<% end %>

app/views/posts/_post.html.erb
<div>
  <p>【メールアドレス】 <%= post.user.email %></p>
  <p>【内容】 <%= post.title %></p>
  <p>
    <%= link_to "詳細", post %>
    <%= link_to "編集", edit_post_path(post) %>
    <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
</div>
<hr>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= render @posts %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】 <%= @post.user.email %></p>
<p>【内容】 <%= @post.content %></p>
<p>【作成日時】 <%= l @post.created_at %></p>
<p>
<%= link_to "編集", edit_post_path(@post) %>
<%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか?" } %>
</p>
<p><%= link_to "投稿一覧へ", posts_path %></p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>